encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("newpage/", views.newpage, name="newpage"),
    path("wiki/<str:name>", views.entry, name="entry"),
    path("wiki/edit/<str:name>", views.edit, name="edit"),
    path("search/", views.search, name="search"),
    path("randompage/", views.randompage, name="randompage")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from . import util
from django.contrib import messages
from markdown2 import Markdown
import random

markdowner = Markdown()

# Show entries list
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


# Add a new page:
def newpage(request):
    if request.method == "POST":
        title = request.POST.get("title")
        content = request.POST.get("content")

        if not title or not content:
            messages.add_message(request, messages.INFO, 'Must input CONTENT and TITLE.')
        
        elif util.get_entry(title) != None:
            messages.add_message(request, messages.INFO, 'Encyclopedia Entry have already existed. Find and edit content.')
        
        else:
            util.save_entry(title, content)
            return render(request, "encyclopedia/entry.html", { 
                "content": markdowner.convert(content),
                "name": title
            })


    return render(request, "encyclopedia/newpage.html")

# Display entry content
def entry(request, name):
    
    # Check path of entry
    if util.get_entry(name) == None:
        messages.add_message(request, messages.INFO, 'REQUESTED PAGE WAS NOT FOUND.')
        return render(request, "encyclopedia/error.html", {
            "messages": messages
        })
    else:
        content = markdowner.convert(util.get_entry(name))

        return render(request, "encyclopedia/entry.html", { 
            "content": content,
            "name": name
        })

# Edit entry
def edit(request, name):

    content = util.get_entry(name)
    print(content)


    # Check if method is POST
    if request.method == "POST":

        content = request.POST.get("content")
        
        if not content:
            messages.add_message(request, messages.INFO, 'Must input CONTENT')

        else:
            util.save_entry(name, content)
            content = markdowner.convert(util.get_entry(name))

            # Redirect user to home page
            return render(request, "encyclopedia/entry.html", {
                "name": name,
                "content": content
            })

    return render(request, "encyclopedia/edit.html", {
        "name": name,
        "content": content
    })

# Search for entry
def search(request):

    # Check if method is POST
    if request.method == "POST":
        src = request.POST.get("q")

        # Convert search content to lowercase with no spaces
        search = src.lower().replace(" ","")

        # If submitted content is blank
        if not search:
            return render(request, "encyclopedia/index.html", {
                "entries": util.list_entries()
            })

        else:
            entries = util.list_entries()
            results = []

            # Loop through entries list
            for item in entries:

                # If search content == entry title, render entry page
                if search == item.lower().replace(" ",""):
                    content = markdowner.convert(util.get_entry(item))
                    
                    return render(request, "encyclopedia/entry.html", { 
                        "content": content,
                        "name": item
                    })

                # If not, add title similar entries to new list to display
                elif search in item.lower().replace(" ",""):

                    results.append(item)

            return render(request, "encyclopedia/search.html", {
                "results": results
            })

# Access random entry page
def randompage(request):

    entries = util.list_entries()

    title = random.choice(entries)

    content = markdowner.convert(util.get_entry(title))

    return render(request, "encyclopedia/entry.html", { 
        "content": content,
        "name": title
    })

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  {{ name }}
{% endblock %}

{% block body %}

  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
          <li id="message" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}

  <form action="{% url 'encyclopedia:edit' name %}" method="post">
    {% csrf_token %}
    <textarea autofocus class="content" name="content">{{ content }}</textarea><br>
    <input type="submit">
  </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ name | safe }}
{% endblock %}

{% block body %}
    {{ content | safe }}<br>
    <a href="{% url 'encyclopedia:edit' name %}">
        <button>Edit</button>
    </a>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    ERROR
{% endblock %}

{% block body %}

    <h1 style="color: red;">NOT FOUND</h1>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
             <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li> 
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'encyclopedia/styles.css' %}">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <!-- Create New Page -->
                    <a href="{% url 'encyclopedia:newpage' %}">New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randompage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    newpage
{% endblock %}

{% block body %}
    <h1>New Page:</h1>
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li id="message" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    <form action="{% url 'encyclopedia:newpage' %}" method="post">
        {% csrf_token %}
        <label for="title">Title</label><br>
        <textarea autofocus name="title" id="title"></textarea><br>
        <label for="content">Content</label><br>
        <textarea name="content" id="content"></textarea><br>
        <input type="submit" value="SAVE">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>

    <ul>
        {% for result in results %}
             <li><a href="{% url 'encyclopedia:entry' result %}">{{ result }}</a></li> 
        {% endfor %}
    </ul>

{% endblock %}